reficlear.o: reficlear.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
rstrlen.o: rstrlen.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
rstrcmp.o: rstrcmp.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
refiprint.o: refiprint.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h \
 /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/include/stdarg.h \
 /usr/share/mingw-w64/include/stdarg.h \
 /usr/share/mingw-w64/include/_mingw_stdarg.h \
 /usr/share/mingw-w64/include/vadefs.h \
 /usr/share/mingw-w64/include/_mingw.h \
 /usr/share/mingw-w64/include/_mingw_mac.h \
 /usr/share/mingw-w64/include/_mingw_secapi.h \
 /usr/share/mingw-w64/include/sdks/_mingw_directx.h \
 /usr/share/mingw-w64/include/sdks/_mingw_ddk.h
rstrcpy.o: rstrcpy.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
wrstrcat.o: wrstrcat.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
rstrcat.o: rstrcat.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
refizeromem.o: refizeromem.c include/refilib.h \
 ../../boot/include/refi/refi.h ../../boot/include/refi/reficheck.h \
 ../../boot/include/refi/refidefs.h ../../boot/include/refi/refienum.h \
 ../../boot/include/refi/refiguid.h ../../boot/include/refi/refistat.h \
 ../../boot/include/refi/refiprotapi.h ../../boot/include/refi/refiprot.h \
 ../../boot/include/refi/refiapi.h ../../boot/include/refi/refitab.h
guid.o: guid.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
wrstrlen.o: wrstrlen.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
wrstrcmp.o: wrstrcmp.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
wrstrcpy.o: wrstrcpy.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
refierror.o: refierror.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
refiinit.o: refiinit.c include/refilib.h ../../boot/include/refi/refi.h \
 ../../boot/include/refi/reficheck.h ../../boot/include/refi/refidefs.h \
 ../../boot/include/refi/refienum.h ../../boot/include/refi/refiguid.h \
 ../../boot/include/refi/refistat.h ../../boot/include/refi/refiprotapi.h \
 ../../boot/include/refi/refiprot.h ../../boot/include/refi/refiapi.h \
 ../../boot/include/refi/refitab.h
